const productData = [
  {
    name: "Pure Copper Water Bottle",
    image: "https://m.media-amazon.com/images/I/61y9+yUsCIL._SY355_.jpg",
    brand: "AYURVEDACOPPER",
    price: 470,
    inStock: true,
    fastDelivery: true,
  },
  {
    name: "Aroma Diffuser",
    image: "https://m.media-amazon.com/images/I/81FK42UN80L._SX450_.jpg",
    brand: "FnP CL",
    price: 385,
    inStock: true,
    fastDelivery: true,
  },
  {
    name: "Aroma Diffuser Oil",
    image: "https://m.media-amazon.com/images/I/71nVBNnsd+L._SX466_.jpg",
    brand: "pure",
    price: 437,
    inStock: true,
    fastDelivery: true,
  },
  {
    name: "Handi/Earthen Pot for Cooking with Lid",
    image: "https://m.media-amazon.com/images/I/618R7-EYD7L._SX450_.jpg",
    brand: "Craftsman India online",
    price: 785,
    inStock: true,
    fastDelivery: true,
  },
  {
    name: "Striped Traditional Rug",
    image: "https://m.media-amazon.com/images/I/81fWF1ebC7L._SX569_.jpg",
    brand: "Generic",
    price: 889,
    inStock: true,
    fastDelivery: true,
  },
  {
    name: "Handmade Rug/Dari",
    image:
      "https://images-eu.ssl-images-amazon.com/images/I/81DgPBMYT0S._AC_UL160_SR160,160_.jpg",
    brand: "The Crafts Heaven",
    price: 499,
    inStock: false,
    fastDelivery: true,
  },
  {
    name: "Skin-Tint Mattifying Foundation",
    image: "https://m.media-amazon.com/images/I/51cqTwDdIpS._SY450_.jpg",
    brand: "Ruby's Organics",
    price: 1568,
    inStock: false,
    fastDelivery: false,
  },
  {
    name: "SoulTree Ayurvedic Mascara ",
    image: "https://m.media-amazon.com/images/I/513mMNFIAQL._SY450_.jpg",
    brand: "SoulTree",
    price: 950,
    inStock: true,
    fastDelivery: false,
  },
  {
    name: "Ayurvedic Pure Black Kajal ",
    image: "https://m.media-amazon.com/images/I/31xZsjrD3dL._SY450_.jpg",
    brand: "SoulTree",
    price: 695,
    inStock: true,
    fastDelivery: true,
  },
  {
    name: "Organic Neem Basil Face Wash",
    image: "https://m.media-amazon.com/images/I/71tgnfpRb5L._SY450_.jpg",
    brand: "Rustic Art",
    price: 190,
    inStock: true,
    fastDelivery: false,
  },
  {
    name: "Black Rice Leave-in Conditioner",
    image: "https://m.media-amazon.com/images/I/51ec8jsnfEL._SY450_.jpg",
    brand: "FOR8",
    price: 398,
    inStock: true,
    fastDelivery: true,
  },
  {
    name: "Heena Fresh Powder Hair Color",
    image: "https://m.media-amazon.com/images/I/41uDb-MjBvL._SY450_.jpg",
    brand: "Biotique",
    price: 199,
    inStock: true,
    fastDelivery: true,
  },
]
module.exports = { productData }
