const productData = [
  {
    name: "Brown Shirt",
    description: "Brown T-Shirt for Women",
    price: 1240,
    gender: "women",
    type: "shirt",
    image: "https://image.ibb.co/kOhL6k/img1.jpg",
    category: "clothes",
    inStock: true,
    fastDelivery: true,
  },
  {
    name: "Light Brown Shirt",
    description: "Light Brown Shirt for Women",
    price: 364,
    gender: "women",
    type: "shirt",
    image: "https://image.ibb.co/nNmKz5/img2.jpg",
    category: "clothes",
    inStock: true,
    fastDelivery: false,
  },
  {
    name: "Women Grey Shirt",
    description: "Grey Shirt for Women",
    price: 1094,
    gender: "women",
    type: "shirt",
    image: "https://image.ibb.co/n6iMCQ/img3.jpg",
    category: "clothes",
    inStock: false,
    fastDelivery: true,
  },
  {
    name: "Warm Shirt Women",
    description: "Woolen Hoodie Women",
    price: 1460,
    gender: "women",
    type: "shirt",
    image: "https://image.ibb.co/dVfORk/img4.jpg",
    category: "clothes",
    inStock: true,
    fastDelivery: true,
  },
  {
    name: "Women Grey Shirt",
    description: "Light Grey Shirt for Women",
    price: 364,
    gender: "women",
    type: "shirt",
    image: "https://image.ibb.co/jpMxmk/img5.jpg",
    category: "clothes",
    inStock: true,
    fastDelivery: false,
  },
  {
    name: "Women Red/Brown Shirt",
    description: "Red/Brown Blouse for Women",
    price: 1459,
    gender: "women",
    type: "blouse",
    image: "https://image.ibb.co/mJppz5/img6.jpg",
    category: "clothes",
    inStock: false,
    fastDelivery: true,
  },
  {
    name: "Dark Grey Shirt Women",
    description: "Dark Grey Shirt for Women",
    price: 438,
    gender: "women",
    type: "shirt",
    image: "https://image.ibb.co/eZiSmk/img7.jpg",
    category: "clothes",
    inStock: true,
    fastDelivery: false,
  },
  {
    name: "White Shirt Women",
    description: "White Shirt for Women",
    price: 1094,
    gender: "women",
    type: "shirt",
    image: "https://image.ibb.co/dyCysQ/img8.jpg",
    category: "clothes",
    inStock: true,
    fastDelivery: true,
  },
  {
    name: "Black Shirt Women",
    description: "Black Shirt for Women",
    price: 1532,
    gender: "women",
    type: "shirt",
    image: "https://image.ibb.co/eOYre5/img10.jpg",
    category: "clothes",
    fastDelivery: false,
    inStock: false,
  },
  {
    name: "No Shoulder Hoodie",
    description: "Hoodie for Women",
    price: 364,
    gender: "women",
    type: "shirt",
    image: "https://image.ibb.co/f6gcK5/img9.jpg",
    category: "clothes",
    inStock: false,
    fastDelivery: false,
  },
  {
    name: "Women Watch Gold",
    description: "Golden Watch for Women",
    price: 3357,
    gender: "women",
    type: "watch",
    image:
      "https://images.pexels.com/photos/69046/watch-wrist-watch-packshot-time-69046.jpeg?w=1260&h=750&auto=compress&cs=tinysrgb",
    category: "accessories",
    inStock: false,
    fastDelivery: true,
  },
  {
    name: "Black Pearl Necklace",
    description: "Black Pearl Necklace for Women",
    price: 1094,
    gender: "women",
    type: "necklace",
    image:
      "https://images.pexels.com/photos/221550/pexels-photo-221550.jpeg?w=1260&h=750&auto=compress&cs=tinysrgb",
    category: "accessories",
    inStock: true,
    fastDelivery: false,
  },
  {
    name: "Man Black Shirt",
    description: "Black T-Shirt for Men",
    price: 802,
    gender: "men",
    type: "shirt",
    category: "clothes",
    image:
      "https://images.pexels.com/photos/7533329/pexels-photo-7533329.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    inStock: false,
    fastDelivery: false,
  },
  {
    name: "Man Grey Tanktop",
    description: "Grey Tanktop for Men",
    price: 1094,
    gender: "men",
    type: "shirt",
    category: "clothes",
    image:
      "https://images.pexels.com/photos/10346849/pexels-photo-10346849.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    inStock: false,
    fastDelivery: true,
  },
  {
    name: "Man White Shirt",
    description: "White Shirt for Men",
    price: 1532,
    gender: "men",
    image:
      "https://images.pexels.com/photos/7129660/pexels-photo-7129660.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
    type: "shirt",
    category: "clothes",
    inStock: false,
    fastDelivery: true,
  },
  {
    name: "Man Brown Shirt",
    description: "Brown Shirt for Men",
    price: 1021,
    gender: "men",
    image:
      "https://images.pexels.com/photos/5490235/pexels-photo-5490235.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    type: "shirt",
    category: "clothes",
    inStock: true,
    fastDelivery: true,
  },
  {
    name: "Man Black Tie",
    description: "Black Tie for Men",
    price: 1021,
    gender: "men",
    type: "tie",
    image: "http://image.11st.my/g3/2/7/4/6/7/1/1274671_B_V5.jpg",
    category: "accessories",
    inStock: false,
    fastDelivery: false,
  },
  {
    name: "Black Shirt Men",
    description: "Black Shirt for Men",
    price: 729,
    gender: "men",
    image:
      "https://images.pexels.com/photos/5234252/pexels-photo-5234252.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    type: "shirt",
    category: "clothes",
    inStock: false,
    fastDelivery: false,
  },
  {
    name: "4-Pack Man Ties",
    description: "Ties for Men",
    price: 2627,
    gender: "men",
    type: "tie",
    image:
      "http://www.theethicalman.com/uploads/4/8/0/0/4800645/3035404_orig.png",
    category: "accessories",
    inStock: true,
    fastDelivery: true,
  },
  {
    name: "Man Black Tie",
    description: "Black Tie for Men",
    price: 1167,
    gender: "men",
    type: "tie",
    image:
      "http://static.becomegorgeous.com/img/articles/what_does_your_mans_tie_tell_about_his_personality_.jpg",
    category: "accessories",
    inStock: true,
    fastDelivery: false,
  },
]
module.exports = { productData }
